#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set Vim as the default terminal editor
export EDITOR="vim"

export PATH="/usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Shell virtualenvwrapper startup.
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    export WORKON_HOME=$HOME/.virtualenvs
    export PROJECT_HOME=$HOME/Devel
    source /usr/local/bin/virtualenvwrapper.sh
fi

# Enable bash-style comments.
setopt interactivecomments

# Prepends "nocorrect" to avoid zsh's bs correct feature.
#
# zsh: correct 'x' to 'y'[nyae]?
if [ -f ../zsh_nocorrect ]; then
    while read -r COMMAND; do
        alias $COMMAND="nocorrect $COMMAND"
    done < ~/zsh_nocorrect
fi

PATH=$PATH:$HOME/.rvm/bin

# Aliases.
alias l="ls -l --color -X --group-directories-first"
alias ll="ls -la --color -X --group-directories-first"

alias cd..="cd .."
alias ..3="../../../"

alias h='history'
alias j='jobs -l'

# Use MacVim if we're on a Mac.
if [ "$(uname)" = "Darwin" ]; then;
    alias vim="mvim -v"
fi

# GNU Replacements that couldn't be installed with --default-names
alias cal=gcal
