#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set Vim as the default terminal editor.
export EDITOR="vim"

export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Update `$PATH` to include node_modules/.bin executables.
export PATH="$PATH:./node_modules/.bin"

# Update `$PATH` to include Android CLI tools.
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Shell virtualenvwrapper startup.
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
  export WORKON_HOME=$HOME/.virtualenvs
  export PROJECT_HOME=$HOME/Devel
  export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2
  source /usr/local/bin/virtualenvwrapper.sh
fi

# Automatically `workon $env` when we cd into virtualenv dir with .venv
check_virtualenv() {
  if [ -e .venv ]; then
    env=`cat .venv`
    if [ "$env" != "${VIRTUAL_ENV##*/}" ]; then
      echo "Found .venv in directory. Calling: workon ${env}"
      workon $env
    fi
  fi
}

venv_cd() {
  builtin cd "$@" && check_virtualenv
}

# Call check_virtualenv in case opening directly into a directory.
check_virtualenv
alias cd='venv_cd'

# Enable bash-style comments.
setopt interactivecomments

# Prepends "nocorrect" to avoid zsh's bs correct feature.
#
# zsh: correct 'x' to 'y'[nyae]?
if [ -f ~/zsh_nocorrect ]; then
  while read -r COMMAND; do
    alias $COMMAND="nocorrect $COMMAND"
  done < ~/zsh_nocorrect
fi

# docker-compose because always typing docker-compose is arduous.
alias dc=$(which docker-compose)

if [ -f /usr/local/opt/nvm/nvm.sh ]; then
  export NVM_DIR=~/.nvm
  source /usr/local/opt/nvm/nvm.sh
fi

if [ -f ~/.zsh_secrets.zsh ]; then
  source ~/.zsh_secrets.zsh
fi
